server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s #???????????tcp????????
  shutdown: graceful

spring:
  application:
    name: edge-service
  lifecycle:
    timeout-per-shutdown-phase: 15s #??15?????


